apiVersion: v1  # Specifies the API version of Kubernetes being used
kind: Service  # Specifies that this is a definition for a Service
metadata:
  name: # TODO # Sets the name of the Service, used to reference it
spec:
  type: NodePort  # Specifies the type of Service; NodePort makes the Service accessible on a static port on each node
  ports:
    - port: 5001  # The port on which the Service is exposed in the cluster
      targetPort: 5001  # The port on the pod that the Service routes to
      nodePort: 30001  # The port on each node on which this service is exposed (allowed range: 30000-32767)
  selector:
    app: flask-app  # Selector label used to find the pods that the traffic is routed to
